# Step 1


FROM node:10-alpine as build-step



WORKDIR /FIRST-REACT-APP


COPY package.json /FIRST-REACT-APP


RUN npm install


COPY . /FIRST-REACT-APP


RUN npm run build


 


# Stage 2


FROM nginx:1.17.1-alpine


COPY --from=build-step /FIRST-REACT-APP/build /usr/share/nginx/html